version: 3

tasks:
  tailwind-gen:
    dir: ./src/RoomsCalendar.Client
    cmds:
      - npx @tailwindcss/cli -i "./Styles/app.css" -o "./wwwroot/css/app.css"

  tailwind-watch:
    dir: ./src/RoomsCalendar.Client
    cmds:
      - npx @tailwindcss/cli -i "./Styles/app.css" -o "./wwwroot/css/app.css" --watch

  build:
    summary: Build the application
    dir: .
    vars:
      PROJECT_DIR: "./backend/RoomsCalendar.Server"
    cmds:
      - dotnet clean -v quiet
      - dotnet build -c Debug {{.PROJECT_DIR}}

  run:
    summary: Run the application in development mode
    dir: .
    cmds:
      - pnpm exec nx run-many -t=dev

  publish:
    summary: Publish the application for production
    dir: .
    vars:
      PROJECT_DIR: "./backend/RoomsCalendar.Server"
      PUBLISH_DIR: "./publish"
    cmds:
      - dotnet clean -v quiet
      - dotnet publish {{.PROJECT_DIR}} -c Release -o {{.PUBLISH_DIR}}
