version: 3

tasks:
  tailwind-gen:
    dir: ./src/RoomsCalendar.Client
    cmds:
      - npx @tailwindcss/cli -i "./Styles/app.css" -o "./wwwroot/css/app.css"

  tailwind-watch:
    dir: ./src/RoomsCalendar.Client
    cmds:
      - npx @tailwindcss/cli -i "./Styles/app.css" -o "./wwwroot/css/app.css" --watch

  build:
    desc: Build the application
    dir: .
    vars:
      PROJECT_DIR: "./backend/RoomsCalendar.Server"
    cmds:
      - dotnet clean -v quiet
      - dotnet build -c Debug {{.PROJECT_DIR}}

  container:run:
    desc: Run the application in a containerized environment
    dir: .
    vars:
      COMPOSE_FILE: "build/docker-compose.yml"
      ENV_FILE: "build/.env.dev"
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} up --build --abort-on-container-exit

  container:start:
    desc: Start the containerized application
    dir: .
    vars:
      COMPOSE_FILE: "build/docker-compose.yml"
      ENV_FILE: "build/.env.dev"
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} up -d

  container:stop:
    desc: Stop the containerized application
    dir: .
    vars:
      COMPOSE_FILE: "build/docker-compose.yml"
      ENV_FILE: "build/.env.dev"
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} down

  run:
    desc: Run the application in development mode
    dir: .
    cmds:
      - pnpm exec nx run-many -t=dev

  publish:
    desc: Publish the application for production
    dir: .
    vars:
      PROJECT_DIR: "./backend/RoomsCalendar.Server"
      PUBLISH_DIR: "./publish"
    cmds:
      - dotnet clean -v quiet
      - dotnet publish {{.PROJECT_DIR}} -c Release -o {{.PUBLISH_DIR}}
