version: 3

tasks:
  build:
    desc: Build the application
    dir: .
    vars:
      PROJECT_DIR: "./backend/RoomsCalendar.Server"
    cmds:
      - dotnet clean -v quiet
      - dotnet build -c Debug {{.PROJECT_DIR}}

  container:run:
    desc: Run the application in a containerized environment
    dir: .
    vars:
      COMPOSE_FILE: "build/docker-compose.yml"
      ENV_FILE: "build/.env.dev"
    cmds:
      - defer:
          task: container:stop
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} up --build --abort-on-container-exit

  container:start:
    desc: Start the containerized application
    dir: .
    vars:
      COMPOSE_FILE: "build/docker-compose.yml"
      ENV_FILE: "build/.env.dev"
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} up -d

  container:stop:
    desc: Stop the containerized application
    dir: .
    vars:
      COMPOSE_FILE: "build/docker-compose.yml"
      ENV_FILE: "build/.env.dev"
    cmds:
      - docker compose -f {{.COMPOSE_FILE}} --env-file {{.ENV_FILE}} down

  run:
    desc: Run the application in development mode
    dir: .
    cmds:
      - pnpm exec nx run-many -t=dev
